name: Ejecutar .jar

on: [push]

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Puedes especificar la versión de Java que necesites
        distribution: 'adopt'

    - name: Run .jar file
      run: java -jar  /target/Carpeta-1.0-SNAPSHOT.jar
